# This is a basic workflow that is manually triggered
name: asv-github-actions

on:
  push:
    branches: 
      - asv-start
jobs:
  run-benchmarks:
    runs-on: ubuntu-18.04
    steps:
      - name: Git clone sunpy repo
        uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
        
      - name: List current folder
        run : ls -la
      
      - name: Check Python version
        run : python --version
        
      - name: Install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install asv virtualenv
          
      - name: Add machine info
        run : asv machine --machine GH-Actions --os ubuntu-18.04 --arch x64 --cpu unknown --ram unknown
        
      - name: Run benchmarks
        run : asv run
  
#  echo-asv-run:
#    needs: clone-repo
#    runs-on: ubuntu-latest
#    steps:
#    - name: Print ASV running benchmarks commands
#      run : echo "Running commands -- asv run, asv dev"
