# This is a basic workflow that is manually triggered
name: asv-github-actions

on:
  push:
    branches: 
      - asv-start
jobs:
  check-benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone sunpy repo
        uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - name: List current folder
        run : ls -la
      
      - name: Check Python version
        run : python --version
        
      - name: Install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install asv virtualenv
          pip install -e ./
          
      - name: Run Sunpy example
        run: python examples/units_and_coordinates/constants_reference.py
        
      - name: Check benchmarks
        run : asv check
  
#  echo-asv-run:
#    needs: clone-repo
#    runs-on: ubuntu-latest
#    steps:
#    - name: Print ASV running benchmarks commands
#      run : echo "Running commands -- asv run, asv dev"
