# This is a basic workflow that is manually triggered
name: echo-github-actions

on:
  push:
    branches: 
      - asv-start
jobs:
  echo-asv-check:
    runs-on: ubuntu-latest
    steps:
    - name: Print ASV checking benchmarks command
      run : echo "Checking command -- asv check"
  
  echo-asv-run:
    runs-on: ubuntu-latest
    steps:
    - name: Print ASV running benchmarks commands
      run : echo "Running commands -- asv run, asv dev"
