# This is a basic workflow that is manually triggered
name: echo-github-actions

on:
  push:
    branches: 
      - asv-start
jobs:
  clone-repo-install-asv-sunpy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone sunpy repo
        uses: actions/checkout@v2
        
      - name: List current folder
        run : ls -la
      
      - name: Check Python version
        run : python --version
        
      - name: Install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install asv sunpy
  
  echo-asv-run:
    needs: clone-repo
    runs-on: ubuntu-latest
    steps:
    - name: Print ASV running benchmarks commands
      run : echo "Running commands -- asv run, asv dev"
